# Work in progress. Should deploy CDK stack to AWS on push to master

name: Deploy to AWS

on:
  push:
    branches: [master]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install cdk dependencies
        run: npm ci
        working-directory: ./infrastructure
      - run: sudo apt-get install zip
      - run: zip build.zip payment_api.py
        working-directory: ./paymentApi
      - run: pip install -r requirements.txt --system --target='./dependencies/python'
        working-directory: ./paymentApi
      - run: zip -r ../dependencies.zip ./*
        working-directory: ./paymentApi/dependencies
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: "diff"
          actions_comment: true
          working_dir: infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
